version: "3"
services:
  db:
    container_name: database-modelo
    image: postgres:11.2-alpine
    restart: always
    env_file: .env
    volumes:
      - ./modelo-postgres-data:/var/lib/postgresql/data
    ports:
      - 5439:5432

  api_modelo:
    container_name: api-modelo
    build: .
    env_file: 
        - .env
    # image: api_ptrf
    command: "gunicorn config.wsgi:application --bind=0.0.0.0:8001 -w 8"
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis_modelo
    volumes:
      - ./staticfiles:/code/staticfiles
    links:
    - db:db   
    
  celery_modelo:
    build: .
    container_name: celery-modelo
    restart: always
    # image: api_modelo
    command: "celery -A config worker --loglevel=info --concurrency=3 -n worker1@%h"
    env_file: .env
    depends_on:
      - redis_modelo

  redis_modelo:
    image: redis:5.0
    container_name: redis-modelo
    restart: always
    ports:
        - "6388:6379"

networks:
  default:
    external:
      name: modelo-network